# Generated by Django 5.0.2 on 2026-01-02 04:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0009_delete_dashboard1_delete_dashboard2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRevenue',
            fields=[
            ],
            options={
                'verbose_name': '최고매출',
                'verbose_name_plural': '최고매출',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard1',
            fields=[
            ],
            options={
                'verbose_name': '병원 현황(일평균)',
                'verbose_name_plural': '병원 현황(일평균)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard3',
            fields=[
            ],
            options={
                'verbose_name': '비급여 치료',
                'verbose_name_plural': '비급여 치료',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
            ],
            options={
                'verbose_name': '병원 현황(일평균)',
                'verbose_name_plural': '병원 현황(일평균)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
            ],
            options={
                'verbose_name': '그래프 현황',
                'verbose_name_plural': '그래프 현황',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
