# Generated by Django 5.0.2 on 2026-01-07 01:36

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('record', '0012_remove_manualrecord_급여_roomrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERD',
            fields=[
            ],
            options={
                'verbose_name': 'ERD',
                'verbose_name_plural': 'ERD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.globalstatistics',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
