# Generated by Django 5.0.2 on 2025-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('chart_number', models.IntegerField(db_index=True, unique=True, verbose_name='차트번호')),
                ('visit_at', models.DateTimeField(db_index=True, help_text='YYYY-MM 형식', max_length=7, verbose_name='내원일')),
                ('visit_type', models.CharField(blank=True, help_text='신환/재진/90일초진 등', max_length=20, verbose_name='초재')),
                ('patient_name', models.CharField(max_length=100, verbose_name='수진자명')),
                ('patient_id', models.CharField(blank=True, help_text='주민등록번호', max_length=50, verbose_name='주민번호')),
                ('insurance_type', models.TextField(blank=True, help_text='예: 국민건강보험, 보호1종  등', verbose_name='보험유형')),
                ('room', models.CharField(db_index=True, max_length=100, verbose_name='진료실')),
                ('doctor_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='담당의')),
            ],
            options={
                'verbose_name': '환자 진료 기록',
                'verbose_name_plural': '환자 진료 기록',
                'ordering': ['-created_at', 'patient_name'],
                'indexes': [models.Index(fields=['created_at', 'room'], name='record_pati_created_b9e68e_idx'), models.Index(fields=['patient_name'], name='record_pati_patient_1a7cf7_idx')],
            },
        ),
    ]
