# Generated by Django 5.0.2 on 2025-12-17 03:39

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='마감일')),
                ('급여', models.IntegerField(default=0, verbose_name='급여')),
                ('비급여', models.IntegerField(default=0, verbose_name='비급여')),
                ('조합청구액', models.IntegerField(default=0, verbose_name='조합청구액')),
                ('단위절사', models.IntegerField(default=0, verbose_name='100/100미만 총액')),
                ('전액본인', models.IntegerField(default=0, verbose_name='장애인기금/전액본인')),
                ('미수_발생금액', models.IntegerField(default=0, verbose_name='미수발생 금액')),
                ('미수_발생건수', models.IntegerField(default=0, verbose_name='미수발생 건수')),
                ('미수_입금금액', models.IntegerField(default=0, verbose_name='미수입금 금액')),
                ('미수_입금건수', models.IntegerField(default=0, verbose_name='미수입금 건수')),
            ],
            options={
                'verbose_name': '마감일지',
                'verbose_name_plural': '마감일지',
                'ordering': ['-date'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard1',
            fields=[
            ],
            options={
                'verbose_name': '병원 현황(일평균)',
                'verbose_name_plural': '3. 병원 현황(일평균)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard2',
            fields=[
            ],
            options={
                'verbose_name': '그래프 현황',
                'verbose_name_plural': '4. 그래프 현황',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard3',
            fields=[
            ],
            options={
                'verbose_name': '비급여 치료',
                'verbose_name_plural': '5. 비급여 치료',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard4',
            fields=[
            ],
            options={
                'verbose_name': '환자 차트',
                'verbose_name_plural': '환자 차트',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard5',
            fields=[
            ],
            options={
                'verbose_name': '최고 매출',
                'verbose_name_plural': '1. 최고 매출',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard6',
            fields=[
            ],
            options={
                'verbose_name': '병원 일지',
                'verbose_name_plural': '2. 병원 일지',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.patientrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patientrecord',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FormDaily',
            fields=[
            ],
            options={
                'verbose_name': '마감일지',
                'verbose_name_plural': '마감일지',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('record.manualrecord',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
