# Generated by Django 5.0.2 on 2025-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_manualrecord_dashboard1_dashboard2_dashboard3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrecord',
            name='excel_file',
            field=models.FileField(blank=True, help_text='환자 진료 기록 엑셀 파일 (.xlsx, .xls)', null=True, upload_to='manual_records/', verbose_name='엑셀 파일'),
        ),
    ]
