# Generated by Django 5.0.2 on 2025-12-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_manualrecord_excel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDaily',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='manualrecord',
            name='medical_record_file',
            field=models.FileField(blank=True, help_text='환자 진료 기록 엑셀 파일 (.xlsx, .xls)', null=True, upload_to='file/', verbose_name='일일환자집계'),
        ),
        migrations.AddField(
            model_name='manualrecord',
            name='visit_source_file',
            field=models.FileField(blank=True, help_text='내원경로 기록 엑셀 파일 (.xlsx, .xls)', null=True, upload_to='file/', verbose_name='일일내원경로'),
        ),
    ]
