# Generated by Django 5.0.2 on 2025-12-18 05:11

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_delete_formdaily_remove_manualrecord_excel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecord',
            name='medical_record_file',
            field=models.FileField(blank=True, help_text='환자 진료 기록 엑셀 파일 (.xlsx, .xls)', null=True, upload_to=record.models.upload_to_folder, verbose_name='일일환자집계'),
        ),
        migrations.AlterField(
            model_name='manualrecord',
            name='visit_source_file',
            field=models.FileField(blank=True, help_text='내원경로 기록 엑셀 파일 (.xlsx, .xls)', null=True, upload_to=record.models.upload_to_folder, verbose_name='일일내원경로'),
        ),
    ]
