# Generated by Django 5.0.2 on 2025-12-19 06:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_manualrecord_medical_record_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard1',
            options={'verbose_name': '병원 현황(일평균)', 'verbose_name_plural': '병원 현황(일평균)'},
        ),
        migrations.AlterModelOptions(
            name='dashboard2',
            options={'verbose_name': '그래프 현황', 'verbose_name_plural': '그래프 현황'},
        ),
        migrations.AlterModelOptions(
            name='dashboard3',
            options={'verbose_name': '비급여 치료', 'verbose_name_plural': '비급여 치료'},
        ),
        migrations.AlterModelOptions(
            name='dashboard5',
            options={'verbose_name': '최고 매출', 'verbose_name_plural': '최고 매출'},
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='manual_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='record.manualrecord', verbose_name='마감일지'),
        ),
        migrations.CreateModel(
            name='VisitChannelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('channel', models.TextField(help_text='예: 인터넷, 간판, 소개', verbose_name='내원경로')),
                ('chart_number', models.IntegerField(db_index=True, unique=True, verbose_name='차트번호')),
                ('visit_at', models.DateTimeField(db_index=True, help_text='YYYY-MM 형식', max_length=7, verbose_name='내원일')),
                ('visit_type', models.CharField(blank=True, help_text='신환/재진/90일초진 등', max_length=20, verbose_name='초재')),
                ('patient_name', models.CharField(max_length=100, verbose_name='수진자명')),
                ('insurance_type', models.TextField(blank=True, help_text='예: 국민건강보험, 보호1종  등', verbose_name='보험유형')),
                ('room', models.CharField(db_index=True, max_length=100, verbose_name='진료실')),
                ('doctor_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='담당의')),
                ('manual_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_channel_records', to='record.manualrecord', verbose_name='마감일지')),
            ],
            options={
                'verbose_name': '내원 경로',
                'verbose_name_plural': '내원 경로',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'room'], name='record_visi_created_ef3134_idx'), models.Index(fields=['patient_name'], name='record_visi_patient_012556_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
