# Generated by Django 5.0.2 on 2025-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_dashboard1_options_alter_dashboard2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard6',
            options={'verbose_name': '병원 현황(일평균)', 'verbose_name_plural': '병원 현황(일평균)'},
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='chart_number',
            field=models.IntegerField(db_index=True, verbose_name='차트번호'),
        ),
        migrations.AlterField(
            model_name='visitchannelrecord',
            name='chart_number',
            field=models.IntegerField(db_index=True, verbose_name='차트번호'),
        ),
    ]
