# Generated by Django 5.0.2 on 2025-12-30 00:58

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models
from django.db.models import Q


def populate_statistics(apps, schema_editor):
    """기존 ManualRecord 데이터로부터 통계 생성"""
    ManualRecord = apps.get_model('record', 'ManualRecord')
    DailyStatistics = apps.get_model('record', 'DailyStatistics')
    MonthlyStatistics = apps.get_model('record', 'MonthlyStatistics')
    GlobalStatistics = apps.get_model('record', 'GlobalStatistics')
    PatientRecord = apps.get_model('record', 'PatientRecord')
    VisitChannelRecord = apps.get_model('record', 'VisitChannelRecord')

    from collections import defaultdict

    # 모든 ManualRecord 처리
    manual_records = ManualRecord._default_manager.all()
    monthly_data = defaultdict(lambda: {
        'daily_stats': [],
        'year': 0,
        'month': 0
    })

    print(f"총 {manual_records.count()}개의 마감일지 처리 중...")

    for mr in manual_records:
        # 총매출 계산
        total_revenue = (
            mr.급여 + mr.비급여 + mr.조합청구액 + mr.단위절사 + mr.전액본인
            - mr.미수_발생금액 + mr.미수_입금금액
        )

        # 환자 통계
        patient_records = PatientRecord._default_manager.filter(manual_record=mr)
        new_count = patient_records.filter(
            Q(visit_type__icontains='신환') | Q(visit_type__icontains='신')
        ).count()
        revisit_count = patient_records.filter(
            Q(visit_type__icontains='재진') | Q(visit_type__icontains='재')
        ).count()
        ninety_count = patient_records.filter(Q(visit_type__icontains='90')).count()

        # 내원 경로 통계
        visit_records = VisitChannelRecord._default_manager.filter(manual_record=mr)
        channel_counts = {}
        for channel in ['인터넷', '간판', '소개', '전화', '재방문', '기타']:
            channel_counts[channel] = visit_records.filter(channel=channel).count()

        # 일별 통계 생성
        daily_stat = DailyStatistics._default_manager.create(
            manual_record=mr,
            total_revenue=total_revenue,
            new_patient_count=new_count,
            revisit_patient_count=revisit_count,
            ninety_day_patient_count=ninety_count,
            total_patient_count=new_count + revisit_count + ninety_count,
            channel_counts=channel_counts
        )

        # 월별 데이터 누적
        key = (mr.date.year, mr.date.month)
        monthly_data[key]['daily_stats'].append(daily_stat)
        monthly_data[key]['year'] = mr.date.year
        monthly_data[key]['month'] = mr.date.month

    print(f"일별 통계 생성 완료. 총 {len(monthly_data)}개월 처리 중...")

    # 월별 통계 생성
    for key, data in monthly_data.items():
        year = data['year']
        month = data['month']
        daily_stats = data['daily_stats']

        working_days = len(daily_stats)
        total_revenue = sum(ds.total_revenue for ds in daily_stats)
        total_new = sum(ds.new_patient_count for ds in daily_stats)
        total_revisit = sum(ds.revisit_patient_count for ds in daily_stats)
        total_ninety = sum(ds.ninety_day_patient_count for ds in daily_stats)
        total_patients = sum(ds.total_patient_count for ds in daily_stats)

        # 내원 경로 집계
        channel_counts = defaultdict(int)
        for ds in daily_stats:
            for ch, count in ds.channel_counts.items():
                channel_counts[ch] += count

        MonthlyStatistics._default_manager.create(
            year=year,
            month=month,
            working_days=working_days,
            total_revenue=total_revenue,
            avg_daily_revenue=total_revenue // working_days if working_days > 0 else 0,
            total_new_patients=total_new,
            total_revisit_patients=total_revisit,
            total_ninety_patients=total_ninety,
            total_patients=total_patients,
            avg_new_patients=round(total_new / working_days, 1) if working_days > 0 else 0,
            avg_revisit_patients=round(total_revisit / working_days, 1) if working_days > 0 else 0,
            avg_ninety_patients=round(total_ninety / working_days, 1) if working_days > 0 else 0,
            avg_total_patients=round(total_patients / working_days, 1) if working_days > 0 else 0,
            channel_counts=dict(channel_counts),
            fee_per_case=total_revenue // total_patients if total_patients > 0 else 0
        )

    print("월별 통계 생성 완료. 전역 통계 생성 중...")

    # 전역 통계 생성
    max_daily = DailyStatistics._default_manager.order_by('-total_revenue').first()
    if max_daily:
        GlobalStatistics._default_manager.create(
            key='max_daily_revenue',
            value={'amount': max_daily.total_revenue, 'date': str(max_daily.manual_record.date)},
            description='역대 최고 일일 매출'
        )

    min_daily = DailyStatistics._default_manager.filter(total_revenue__gt=0).order_by('total_revenue').first()
    if min_daily:
        GlobalStatistics._default_manager.create(
            key='min_daily_revenue',
            value={'amount': min_daily.total_revenue, 'date': str(min_daily.manual_record.date)},
            description='역대 최저 일일 매출 (0 제외)'
        )

    max_daily_patients = DailyStatistics._default_manager.order_by('-total_patient_count').first()
    if max_daily_patients:
        GlobalStatistics._default_manager.create(
            key='max_daily_patients',
            value={'count': max_daily_patients.total_patient_count, 'date': str(max_daily_patients.manual_record.date)},
            description='역대 최고 일일 환자수'
        )

    max_monthly = MonthlyStatistics._default_manager.order_by('-total_revenue').first()
    if max_monthly:
        GlobalStatistics._default_manager.create(
            key='max_monthly_revenue',
            value={'amount': int(max_monthly.total_revenue), 'year': max_monthly.year, 'month': max_monthly.month},
            description='역대 최고 월간 매출'
        )

    max_monthly_patients = MonthlyStatistics._default_manager.order_by('-total_patients').first()
    if max_monthly_patients:
        GlobalStatistics._default_manager.create(
            key='max_monthly_patients',
            value={'count': max_monthly_patients.total_patients, 'year': max_monthly_patients.year, 'month': max_monthly_patients.month},
            description='역대 최고 월간 환자수'
        )

    print("전역 통계 생성 완료!")


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_dashboard6_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('key', models.CharField(db_index=True, help_text='예: max_daily_revenue, min_daily_revenue 등', max_length=100, unique=True, verbose_name='통계 키')),
                ('value', models.JSONField(default=dict, help_text='JSON 형태로 유연하게 저장', verbose_name='통계 값')),
                ('description', models.TextField(blank=True, help_text='이 통계의 의미', verbose_name='설명')),
            ],
            options={
                'verbose_name': '전역 통계',
                'verbose_name_plural': '전역 통계',
                'ordering': ['key'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('year', models.IntegerField(db_index=True, verbose_name='년도')),
                ('month', models.IntegerField(db_index=True, verbose_name='월')),
                ('working_days', models.IntegerField(default=0, verbose_name='근무 일수')),
                ('total_revenue', models.BigIntegerField(default=0, verbose_name='총매출')),
                ('avg_daily_revenue', models.IntegerField(default=0, verbose_name='일평균 매출')),
                ('total_new_patients', models.IntegerField(default=0, verbose_name='총 신환')),
                ('total_revisit_patients', models.IntegerField(default=0, verbose_name='총 재진')),
                ('total_ninety_patients', models.IntegerField(default=0, verbose_name='총 90일초진')),
                ('total_patients', models.IntegerField(default=0, verbose_name='총 환자')),
                ('avg_new_patients', models.FloatField(default=0, verbose_name='일평균 신환')),
                ('avg_revisit_patients', models.FloatField(default=0, verbose_name='일평균 재진')),
                ('avg_ninety_patients', models.FloatField(default=0, verbose_name='일평균 90일초진')),
                ('avg_total_patients', models.FloatField(default=0, verbose_name='일평균 총환자')),
                ('channel_counts', models.JSONField(default=dict, verbose_name='내원경로별 건수')),
                ('fee_per_case', models.IntegerField(default=0, verbose_name='건당 진료비')),
            ],
            options={
                'verbose_name': '월별 통계',
                'verbose_name_plural': '월별 통계',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['-year', '-month'], name='record_mont_year_599a39_idx'), models.Index(fields=['-total_revenue'], name='record_mont_total_r_f84d58_idx')],
                'unique_together': {('year', 'month')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('total_revenue', models.IntegerField(db_index=True, default=0, verbose_name='총매출')),
                ('new_patient_count', models.IntegerField(default=0, verbose_name='신환 수')),
                ('revisit_patient_count', models.IntegerField(default=0, verbose_name='재진 수')),
                ('ninety_day_patient_count', models.IntegerField(default=0, verbose_name='90일초진 수')),
                ('total_patient_count', models.IntegerField(default=0, verbose_name='총 환자 수')),
                ('channel_counts', models.JSONField(default=dict, help_text='{"인터넷": 10, "간판": 20, ...}', verbose_name='내원경로별 건수')),
                ('manual_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='record.manualrecord', verbose_name='마감일지')),
            ],
            options={
                'verbose_name': '일별 통계',
                'verbose_name_plural': '일별 통계',
                'ordering': ['-manual_record__date'],
                'indexes': [models.Index(fields=['-total_revenue'], name='record_dail_total_r_5348f3_idx'), models.Index(fields=['manual_record'], name='record_dail_manual__4d3f77_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        # 데이터 마이그레이션: 기존 ManualRecord로부터 통계 생성
        migrations.RunPython(
            populate_statistics,
            reverse_code=migrations.RunPython.noop
        ),
    ]
