# Generated by Django 5.0.2 on 2026-01-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_globalstatistics_monthlystatistics_dailystatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard1',
        ),
        migrations.DeleteModel(
            name='Dashboard2',
        ),
        migrations.DeleteModel(
            name='Dashboard3',
        ),
        migrations.DeleteModel(
            name='Dashboard4',
        ),
        migrations.DeleteModel(
            name='Dashboard5',
        ),
        migrations.DeleteModel(
            name='Dashboard6',
        ),
        migrations.AlterModelOptions(
            name='dailystatistics',
            options={'default_permissions': [], 'ordering': ['-manual_record__date'], 'verbose_name': '일별 통계', 'verbose_name_plural': '일별 통계'},
        ),
    ]
