# Generated by Django 5.0.2 on 2026-01-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_delete_dashboard1_delete_dashboard2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistics',
            name='manual_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_stats', to='record.manualrecord', verbose_name='마감일지'),
        ),
    ]
