# Generated by Django 5.0.2 on 2026-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_alter_dailystatistics_manual_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecord',
            name='date',
            field=models.DateField(db_index=True, verbose_name='마감일'),
        ),
    ]
