# Generated by Django 5.0.2 on 2026-01-07 01:36

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('record', '0011_alter_manualrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualrecord',
            name='급여',
        ),
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('급여', models.IntegerField(default=0, verbose_name='급여')),
                ('manual_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_records', to='record.manualrecord', verbose_name='마감일지')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hospital.room', verbose_name='진료실')),
            ],
            options={
                'verbose_name': '진료실별 급여',
                'verbose_name_plural': '진료실별 급여',
                'ordering': ['room__order', 'room__name'],
                'unique_together': {('manual_record', 'room')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
