# Generated by Django 5.0.2 on 2026-01-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_remove_manualrecord_급여_roomrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomrecord',
            options={'ordering': ['room__order', 'room__name'], 'verbose_name': '진료실별 마감일지', 'verbose_name_plural': '진료실별 마감일지'},
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='단위절사',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='미수_발생건수',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='미수_발생금액',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='미수_입금건수',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='미수_입금금액',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='비급여',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='전액본인',
        ),
        migrations.RemoveField(
            model_name='manualrecord',
            name='조합청구액',
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='단위절사',
            field=models.IntegerField(default=0, verbose_name='100/100미만 총액'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='미수_발생건수',
            field=models.IntegerField(default=0, verbose_name='미수발생 건수'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='미수_발생금액',
            field=models.IntegerField(default=0, verbose_name='미수발생 금액'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='미수_입금건수',
            field=models.IntegerField(default=0, verbose_name='미수입금 건수'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='미수_입금금액',
            field=models.IntegerField(default=0, verbose_name='미수입금 금액'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='비급여',
            field=models.IntegerField(default=0, verbose_name='비급여'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='전액본인',
            field=models.IntegerField(default=0, verbose_name='장애인기금/전액본인'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='조합청구액',
            field=models.IntegerField(default=0, verbose_name='조합청구액'),
        ),
    ]
