# Generated by Django 5.0.2 on 2026-01-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_alter_roomrecord_options_remove_manualrecord_단위절사_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrecord',
            name='total_revenue',
            field=models.IntegerField(default=0, help_text='총진료비 - 미수발생 + 미수입금', verbose_name='총매출'),
        ),
    ]
