# Generated by Django 5.0.2 on 2026-01-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_alter_room_name_room_hospital_and_more'),
        ('record', '0014_manualrecord_total_revenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalstatistics',
            options={'ordering': ['key'], 'verbose_name': '병원별 통계', 'verbose_name_plural': '병원별 통계'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='globalstatistics',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='manualrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_records', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='monthlystatistics',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statistics', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='roomrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_records', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='visitchannelrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_channel_records', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AlterField(
            model_name='globalstatistics',
            name='key',
            field=models.CharField(db_index=True, help_text='예: max_daily_revenue, min_daily_revenue 등', max_length=100, verbose_name='통계 키'),
        ),
        migrations.AlterUniqueTogether(
            name='globalstatistics',
            unique_together={('hospital', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='manualrecord',
            unique_together={('hospital', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistics',
            unique_together={('hospital', 'year', 'month')},
        ),
    ]
