# Generated by Django 5.0.2 on 2026-01-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_populate_default_hospital'),
        ('record', '0015_alter_globalstatistics_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='manualrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hospital', 'date'), name='unique_active_manual_record_per_hospital_date'),
        ),
    ]
