# Generated by Django 5.0.2 on 2026-01-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_change_unique_constraint_to_exclude_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrecord',
            name='hospital',
        ),
    ]
