# Generated by Django 5.0.2 on 2026-01-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_alter_room_name_room_hospital_and_more'),
        ('user', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='hospital.hospital', verbose_name='현재 활성 병원'),
        ),
        migrations.AddField(
            model_name='user',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='users', to='hospital.hospital', verbose_name='소속 병원'),
        ),
    ]
