# Generated by Django 5.0.2 on 2026-01-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_current_hospital_user_hospitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_hospital',
        ),
    ]
