# Generated by Django 5.0.2 on 2026-01-09 05:19

from django.db import migrations


def create_role_groups(apps, schema_editor):
    """대표, 관리자 그룹 생성 및 모든 권한 부여"""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # 모든 권한 가져오기
    all_permissions = Permission.objects.all()

    # 대표 그룹 생성
    representative_group, _ = Group.objects.get_or_create(name="대표")
    representative_group.permissions.set(all_permissions)

    # 관리자 그룹 생성
    manager_group, _ = Group.objects.get_or_create(name="관리자")
    manager_group.permissions.set(all_permissions)


def reverse_role_groups(apps, schema_editor):
    """롤백 시 그룹 삭제"""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["대표", "관리자"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_current_hospital'),
        ('auth', '__latest__'),  # Permission 모델 의존성
    ]

    operations = [
        migrations.RunPython(create_role_groups, reverse_role_groups),
    ]
