# Generated by Django 5.0.2 on 2026-01-07 01:36

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='진료실명')),
                ('is_active', models.BooleanField(default=True, help_text='비활성화 시 급여 입력에서 제외됩니다', verbose_name='활성화')),
                ('order', models.IntegerField(default=0, help_text='탭에 표시될 순서', verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '진료실',
                'verbose_name_plural': '진료실',
                'ordering': ['order', 'name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
