# Generated by Django 5.0.2 on 2026-01-09 04:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='병원명')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='병원 코드')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='대표 전화')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '병원',
                'verbose_name_plural': '병원',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='진료실명'),
        ),
        migrations.AddField(
            model_name='room',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hospital', 'name')},
        ),
    ]
