# Generated by Django 5.0.2 on 2026-01-09 04:28

from django.db import migrations


def populate_default_hospital(apps, schema_editor):
    """기본 병원 생성 및 기존 데이터 할당"""
    Hospital = apps.get_model("hospital", "Hospital")
    Room = apps.get_model("hospital", "Room")
    ManualRecord = apps.get_model("record", "ManualRecord")
    RoomRecord = apps.get_model("record", "RoomRecord")
    PatientRecord = apps.get_model("record", "PatientRecord")
    VisitChannelRecord = apps.get_model("record", "VisitChannelRecord")
    DailyStatistics = apps.get_model("record", "DailyStatistics")
    MonthlyStatistics = apps.get_model("record", "MonthlyStatistics")
    GlobalStatistics = apps.get_model("record", "GlobalStatistics")
    User = apps.get_model("user", "User")

    # 기본 병원 생성 (마이그레이션 중에는 _default_manager 사용)
    try:
        default_hospital = Hospital._default_manager.get(code="OPN-APG")
        created = False
    except Hospital.DoesNotExist:
        default_hospital = Hospital._default_manager.create(
            code="OPN-APG", name="오픈 정형외과 압구정", is_active=True
        )
        created = True

    if created:
        print(f"✅ 기본 병원 생성: {default_hospital.name} ({default_hospital.code})")
    else:
        print(f"✅ 기본 병원 이미 존재: {default_hospital.name}")

    # 모든 기존 데이터를 기본 병원에 할당 (_default_manager 사용)
    Room._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    ManualRecord._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    RoomRecord._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    PatientRecord._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    VisitChannelRecord._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    DailyStatistics._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    MonthlyStatistics._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)
    GlobalStatistics._default_manager.filter(hospital__isnull=True).update(hospital=default_hospital)

    print(f"✅ 모든 기존 데이터를 {default_hospital.name}에 할당 완료")

    # 슈퍼유저에게 병원 할당
    for user in User._default_manager.filter(is_superuser=True):
        user.hospitals.add(default_hospital)
        if not user.current_hospital:
            user.current_hospital = default_hospital
            user.save()
        print(f"✅ 슈퍼유저 {user.username}에게 병원 할당 완료")


def reverse_populate(apps, schema_editor):
    """롤백 시 기본 병원 삭제"""
    Hospital = apps.get_model("hospital", "Hospital")
    Hospital._default_manager.filter(code="OPN-APG").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_hospital_alter_room_name_room_hospital_and_more"),
        ("record", "0015_alter_globalstatistics_options_and_more"),
        ("user", "0004_user_current_hospital_user_hospitals"),
    ]

    operations = [
        migrations.RunPython(populate_default_hospital, reverse_populate),
    ]
